travis:
  secure:
    BINSTAR_TOKEN: TVTUmRCN/WduRodcETuiP/3UWxaBMiLaGGGpA4obJx+pOHl2/T4aEoDmbrDzRCkxBwZU+WP5y2PEMt319CBg4NRE9P2+Q5jbHOBbcDwQb+hNsheSNFBRvpjsOt0zeFyoiGkreTUWmRwb9EJgoPDeocvVh5bd8q67pkra3YeSXuM0X29N0FGhCAcSGtJ+X56dCMlezjJZO6vOlqNlhD9yL0ZyWNG6C0IOyLDY6gs9/VcVN/IPQOdCIs173QBUp9e5DCYQuP4O8q9d2um1THKtCszUAiVunj5RfnJIpL8loHNfkkq+SPuiL/P6lj21E01dsIStE0+Zf3hyyRnqOJzX2bEA+baQc5F0zL/aqKU55ESZGiXDw/LeGp3C0UgMNKHiJjM6avtWnibnQSCQizF7of8Bv9RLTFZLYvjGnIwiUeAwxh5w807maOAN8e0WN9DzUTEn5dDI/I6D6NuB59IKKWKQd/bmhxlUrSkfmjvng8B08NC6wDEj+mSd1jHq8iKhmbfA+w4xhLpBrMujr89jqSfCF2UkMmZVg+5hCkD7s59u0GzGdH4wM9Pm01n3qnzZTWcdrWmuJuMtpKwNN3mlFwj1/C8BKF88OSsEw8aRssOidtn39O0JtM23yfH/Hvzo5u9rBEt9uiHOUZkC85o8wWsKrU9wLJlb3YutVb/WFNE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
