travis:
  secure:
    BINSTAR_TOKEN: WlxUxGzx3yozPZgVaUL8Keoq5HYsWjY7EdEJzN38SVXtnaCXDWANYMQ5ZD+H9Po9dVeL1r8sIIWfvVffJ3h5Q1Z2QzU4AWS3c6L49GXaEa5OkavFR5jABzAKCxdqSFyxLHZ3aapYzKQv83mqw5vOAyW0JDUD8w37x/5hGhs7ZokUPQKQ5QmHBJRtMZUtlXmH/BRi4Y973yu//b+plfsiH3vutLesQkt0ZDdnLnowXYMlkBSVv2yyBd59dg1+8MstbFG3oFmDcMyTOAjIrdLvtHYiX0WBBgiKejy80w4h9waPB5NrHnlPYNsQilkxihsO20KQMkylypMzH1PGbuNSg+Bq4Qlh2ixom7Rror5vPZPCBQ149fv+ckFCopd3kbKY1uZTrf4Wq8VbNfwMsPcgEsangO3Xj+8qQjyzBFhOtoqFPDv5EHAywEVuURF+cCALBNX/GH/frNOWInOyxHv1ER39szLXQEDnA1/IfBJUovaO7X0ND3DkZb/ijVDvgxfN1z1b516YgD+/0Gv56nUmCCmjP9lqmW8mgf72F0aW78+eSY6QJ3orlXiZbpPR/ezLK+AWPooPDittN/BKDwZzfhtyCHVyPVnXq+zhKC7DTXINrq7Ls9PF8NGlBEKCzy6AancQJTFer2grnqA5QDASFWa3JPFxmtOd+JC8knC4HmY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
